# Generated by Django 2.2.5 on 2019-09-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=1, max_digits=4)),
                ('distance_type', models.CharField(choices=[('km', 'km'), ('mi', 'mi')], default='mi', max_length=5)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('cutoff_time', models.DateTimeField(verbose_name='cuttoff time')),
                ('total_capacity', models.IntegerField(blank=True, verbose_name='capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='organizer')),
                ('web', models.URLField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('area_code', models.CharField(blank=True, max_length=5, verbose_name='area code')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='phone number')),
                ('photo', models.ImageField(blank=True, default='example.jpg', upload_to='organizer_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('gender', models.CharField(blank=True, choices=[('female', 'F'), ('male', 'M'), ('other', 'other')], default='female', max_length=10)),
                ('birthdate', models.DateTimeField(verbose_name='date of birth')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('area_code', models.CharField(blank=True, max_length=5, verbose_name='area code')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='phone')),
                ('emergency_contact_name', models.CharField(max_length=50, verbose_name='emergency contact name')),
                ('emergency_contact_area_code', models.CharField(max_length=5, verbose_name='emergency contact area code')),
                ('emergency_contact_phone', models.CharField(max_length=10, verbose_name='emergency contact phone')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='registration date')),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Distance')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='venue name')),
                ('address', models.CharField(max_length=255, verbose_name='venue address')),
                ('city', models.CharField(max_length=50, verbose_name='venue city')),
                ('state', models.CharField(max_length=255, verbose_name='venue state')),
                ('zip', models.CharField(max_length=20, verbose_name='venue zip code')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='sub-category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('registrations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Registration')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='event title')),
                ('start', models.DateField(verbose_name='start date')),
                ('end', models.DateField(verbose_name='end date')),
                ('photo', models.ImageField(blank=True, default='example.jpg', upload_to='event_photo')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='capacity')),
                ('description', models.CharField(max_length=2000)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Organizer')),
                ('subcategories', models.ManyToManyField(through='events.Categorization', to='events.SubCategory')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Venue')),
            ],
        ),
        migrations.AddField(
            model_name='distance',
            name='events',
            field=models.ManyToManyField(related_name='distances', to='events.Event'),
        ),
        migrations.AddField(
            model_name='categorization',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='categorization',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.SubCategory'),
        ),
    ]
