# Generated by Django 2.2.5 on 2019-10-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=1, max_digits=4)),
                ('distance_type', models.CharField(choices=[('km', 'km'), ('mi', 'mi')], default='mi', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='event title')),
                ('photo', models.ImageField(blank=True, default='event_photo/IMG_4149.jpg', upload_to='event_photo')),
                ('register', models.URLField(max_length=255, verbose_name='registeration link')),
                ('date', models.DateField(verbose_name='start date')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('state', models.CharField(max_length=3, verbose_name='state')),
                ('zip', models.CharField(max_length=20, verbose_name='zip code')),
                ('web', models.URLField(max_length=255, verbose_name='organizer link')),
                ('distance', models.ManyToManyField(to='events.Distance')),
            ],
        ),
    ]
