# Generated by Django 2.2.5 on 2019-10-28 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField(verbose_name='distance')),
                ('distance_type', models.CharField(blank=True, choices=[('km', 'km'), ('mi', 'mi')], default='mi', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='event title')),
                ('register', models.URLField(max_length=255, verbose_name='registeration link')),
                ('date', models.DateField(verbose_name='start date')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('state', models.CharField(max_length=3, verbose_name='state')),
                ('zip', models.CharField(max_length=20, verbose_name='zip code')),
                ('detail', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='organizer')),
                ('web', models.URLField(blank=True, max_length=255, null=True, verbose_name='web')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='sub category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCatEventM2M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, max_length=255, null=True, verbose_name='photo link')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventDistanceM2M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Distance')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='distance',
            field=models.ManyToManyField(through='events.EventDistanceM2M', to='events.Distance'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='subcategory',
            field=models.ManyToManyField(through='events.SubCatEventM2M', to='events.SubCategory'),
        ),
    ]
